### ISSUE TITLE
Skip URL check if the baseurl is set to about: 

### ISSUE THREAD

**Issue by m8ttyB** [mozilla/pytest-mozwebqa#102]
Default to the behavior provided by <code>--skipurlcheck</code>if the URL is <code>about:</code>.

An example usecase would be when we test the Firefox Health Report where <code>--baseurl=about:healthreport</code>.

**Comment by davehunt** [comment]
[pytest-selenium](https://github.com/davehunt/pytest-selenium/) now uses a fixture for the base URL verification, which can be skipped by overriding the fixture in your test class or a `conftest.py` file.
