### ISSUE TITLE
Pass configuration to setup method

### ISSUE THREAD

**Issue by vaidik** [mozilla/pytest-mozwebqa#108]
Is it possible that we pass configuration as an additional argument to `setup` method the way it works for all the test methods?

Ran into an issue while working on marketplace-tests where having this will be good.

**Comment by davehunt** [comment]
[pytest-selenium](https://github.com/davehunt/pytest-selenium/) now uses fixtures. I'm not sure I really understand the use case here, but I'm going to close this. If there's still a need unfulfilled please open against the aforementioned plugin.
