### ISSUE TITLE
Sauce Labs videos are failing to capture/load

### ISSUE THREAD

**Issue by stephendonner** [mozilla/pytest-mozwebqa#110]
STR:

1. Load http://qa-selenium.mv.mozilla.com:8080/view/Sauce%20Labs/job/marketplace.stage.mobile.saucelabs/35/HTML_Report/?, or any of the failed Sauce Labs jobs
2. Looking at the Web Console, it throws:

[17:24:27.174] GET https://saucelabs.com/jobs/7dd96dc86b374f4787482a4d6d79bd45/video.flv [HTTP/1.1 401 Unauthorized 1184ms]

**Comment by davehunt** [comment]
Videos in the HTML reports were fixed in https://github.com/mozilla/pytest-mozwebqa/commit/52e7541c5b355bb55cac0254d07e10377279859a
