### ISSUE TITLE
Add the ability to use command line user and password for the sauce labs credentials 

### ISSUE THREAD

**Issue by bebef1987** [mozilla/pytest-mozwebqa#118]
We need this to be able to connect Sauce labs and Travis CI together.

We have plans to do something similar with for our tests:
https://saucelabs.com/opensource/travis

**Comment by davehunt** [comment]
Implemented via environment variables in pull #152

**Comment by davehunt** [comment]
We now support environment varaibles and configuration files in [pytest-selenium](https://github.com/davehunt/pytest-selenium/). Closing this issue.
