### ISSUE TITLE
Investigate/fix our verify=False (SNI/SSL-cert-checking support)

### ISSUE THREAD

**Issue by stephendonner** [mozilla/pytest-mozwebqa#132]
We've got verify=False passed in (due to problems in the past -- at least? -- with SNI support for dev/staging servers).  I'm not sure where we are with that, now, but @jgmize wisely suggests that we investigate and, if it works, verify SSL/certs, a la https://bugzilla.mozilla.org/show_bug.cgi?id=1080571

**Comment by davehunt** [comment]
In [pytest-selenium](https://github.com/davehunt/pytest-selenium/) we leave the default behaviour, which is to verify URLs. Let's close this and open an issue against the new plugin if we need to allow verification to be disabled.
