### ISSUE TITLE
ignore ssl cert issues for phantomjs (ghostdriver)

### ISSUE THREAD

**Issue by sashakruglov** [mozilla/pytest-mozwebqa#135]
Hi!

Currently ghostdriver (phantomjs) wont work for sites with invalid ssl cert.
This change should do the trick:
`self.selenium = webdriver.PhantomJS(service_args=['--ignore-ssl-errors=true'])`

**Comment by davehunt** [comment]
I believe this should be supported by capabilties. Searching around I found references to a `phantomjs.cli.args` and `acceptSslCerts`. I'm not sure if they currently work, but this would probably be the best way to support them.
