### ISSUE TITLE
Failures reported as xpasses when conditional xfail is used

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/pytest-mozwebqa#139]
When a test is marked as a conditional xfail, such as:

`@pytest.mark.xfail("'addons.allizom' in config.getvalue('base_url')", reason='https://github.com/mozilla/Addon-Tests/issues/728')`

if the test fails and the condition is not met, rather than this being reported as a failure it is reported as an xpass.

It is believed that the code involved in doing this is at https://github.com/mozilla/pytest-mozwebqa/blob/master/pytest_mozwebqa/html_report.py#L149

**Comment by davehunt** [comment]
We'd either need a way to determine the actual result, or we could evaluate the xfail condition. I'd prefer it if we can get the actual result from pytest somehow.

**Comment by davehunt** [comment]
This is fixed in [pytest-html](https://github.com/davehunt/pytest-html), which is the independent HTML report plugin used in this plugin's successor, [pytest-selenium](https://github.com/davehunt/pytest-selenium)
