### ISSUE TITLE
Flag to run cross broswer in sauce

### ISSUE THREAD

**Issue by sshaar08** [mozilla/pytest-mozwebqa#143]
I have a need to run parallel tests in different broswers would it be possible to pass a flag or something for lets say chrome and firefox?

**Comment by rbillings** [comment]
You can indicate specific browsers as shown in the "Configuration" section here: https://github.com/mozilla/pytest-mozwebqa

**Comment by davehunt** [comment]
The `browsername`, `browserver`, and `platform` command line arguments are passed to Sauce Labs, so these can be any values that they support. If you want to run in multiple configurations I would recommend running the same command with different arguments. You could do this at the same time from another terminal window if you want them running in parallel.
