### ISSUE TITLE
Add a command line option to force the browser window to a particular size

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/pytest-mozwebqa#148]
This can be used to run mobile tests using a desktop browser.

**Comment by davehunt** [comment]
I like this idea. What command line arguments could we use? Do you think it makes sense to support the relative maximized browser window too? I believe we maximize the browser window in a couple of our projects.

How about:
* --browser-width=integer
* --browser-height=integer
* --browser-maximized

We could have a usage check that fails if both maximized and either width or height are specified. We could leave the maximized option for another issue, but I think it's worth considering before we go ahead with this issue.

**Comment by davehunt** [comment]
I also think we should support reading values from environment variables. They could be `BROWSER_WIDTH`, `BROWSER_HEIGHT`, etc.

**Comment by bobsilverberg** [comment]
Yes, those all sound good to me. I think that right now we specify maximized when what we really mean is a minimum window size, so we might move all those suites to using a specific size. Also, our suites that currently specify window size do a check and only resize the window if it's not already large enough. I think that would get quite complicated if we wanted to support that via a min-width / min-height argument, and it seems unnecessary, so I think we should stick with your suggestions above. I just brought it up because it is code that exists now that will be replaced.

**Comment by davehunt** [comment]
This can be done in pytest-selenium by overriding the `selenium` fixture and setting the window size via the API:

```python
import pytest
@pytest.fixture
def selenium(selenium):
    selenium.maximize_window()
    return selenium
```
