### ISSUE TITLE
Add support for Safari

### ISSUE THREAD

**Issue by casschin** [mozilla/pytest-mozwebqa#157]
I tried running some tests on Safari with the mozwebqa plugin and it looks like it's not currently supported.

**Comment by bobsilverberg** [comment]
Thanks for filing the issue, @casschin. This plugin is going into maintenance mode, to be replaced with https://github.com/davehunt/pytest-selenium, so any enhancements would need to be made there. I therefore suggest that you close this issue and open an issue at https://github.com/davehunt/pytest-selenium/issues.

Having said that, I don't think that we (Web QA) have any plans to add support for Safari to the plugin, but we would certainly accept patches if someone else wants to add such support.
