### ISSUE TITLE
Unable to load FF extension

### ISSUE THREAD

**Issue by rarelam** [mozilla/pytest-mozwebqa#159]
Hi, I have supply --browsername=firefox --profilepath=firefox_profile --extension=some.xpi . However my test fail to run with an exception cannot process exception. I have no idea about this exception, I have write an simple remote web driver script with said profile and extension and it worked. 

Please check attachment below for exception trace.

![untitled2](https://cloud.githubusercontent.com/assets/1460421/9784579/8613d898-57de-11e5-9910-e7a322634388.png)

Thank you.

**Comment by davehunt** [comment]
It looks like the plugin is attempting to start a ChromeDriver instead of a FirefoxDriver. Could you try with the beta version of pytest-selenium to see if you can repicate the issue there? https://pypi.python.org/pypi/pytest-selenium/1.0b1

**Comment by rarelam** [comment]
Thanks for your swift response.

Will the command be the same to be parse by pytest-selenium?

**Comment by davehunt** [comment]
It's a bit different, but should be familiar. Try the following:

    py.test --driver Remote --capability browserName Firefox --firefox-profile /path/to/profile --firefox-extension /path/to/extension.xpi

**Comment by rarelam** [comment]
It seem I have something wrong with my configuration. I have no idea how to proceed with this.
Sorry for all the troubles.

![untitled](https://cloud.githubusercontent.com/assets/1460421/9786188/9ffa19f0-57ea-11e5-9469-6da0f0aac864.png)

**Comment by davehunt** [comment]
You'll need to uninstall pytest-mozwebqa because it has command line options that conflict with pytest-selenium. Also, I'm not sure what you're trying to do with your conftest.py but it shouldn't be needed. See http://pytest-selenium.readthedocs.org/en/latest/user_guide.html#quick-start for examples of how to use pytest-selenium.

**Comment by rarelam** [comment]
After uninstall pytest-mozwebqa and deleted conftest.py.

pytest-selenium works! I was able to load firefox profile and firefox path.

But I found a weird issue about pytest-selenium. It is not related to this topic, maybe should open an issue under pytest-selenium.
![unicode](https://cloud.githubusercontent.com/assets/1460421/9809402/78a87012-589a-11e5-8068-f16891213dc3.png)

Thank you for your help. :=)

**Comment by davehunt** [comment]
I'm glad it's working for you. It looks like your log file contains non-ascii characters. Please raise an issue on the pytest-selenium repository. A workaround that might work is setting environment variable `SELENIUM_EXCLUDE_DEBUG` to `logs`.
