### ISSUE TITLE
add a locale attribute

### ISSUE THREAD

**Issue by klrmn** [mozilla/pytest-mozwebqa#40]
if mozwebqa were to either read the locale from the mozwebqa.cfg or the browser, and make it available as mozwebqa.locale, then tests could build urls using "/" + self.testsetup.locale + "/rest_of_url"

**Comment by davehunt** [comment]
We haven't really needed this, but with [pytest-selenium](https://github.com/davehunt/pytest-selenium/) we could now do this by overriding the `base_url` fixture in the project.
