### ISSUE TITLE
Allow keeping the same browser open while running the tests

### ISSUE THREAD

**Issue by Rik** [mozilla/pytest-mozwebqa#62]
My use case is to do something else while the tests run locally. Without this option, the new browsers keep taking the focus.

**Comment by amitverma12** [comment]
@davehunt Hi, Is there any way I can achieve this?  I have to test a page after login and login takes too much time to be repeated with every test. I tried writing a session scoped fixture so that single login is used across all tests but received a ScopeMismatch error (http://stackoverflow.com/q/31500480/975114).

**Comment by davehunt** [comment]
Please try using pytest-selenium (not yet released), which has much better support for fixtures. You should be able to re-implement the selenium fixture as session scoped. Another option would be to trick your application into thinking you've logged in by setting a session cookie - it would be worth speaking to your development team about this.

**Comment by amitverma12** [comment]
@davehunt : Thanks!

**Comment by davehunt** [comment]
I've just tried, and I can reuse the same browser by overriding the `selenium` fixture in [pytest-selenium](https://github.com/davehunt/pytest-selenium/). Note that I still don't recommend this. :wink: 

```python
@pytest.fixture(scope='session')
def selenium(request, capabilities):
    from pytest_selenium.driver import start_driver
    driver = start_driver(request.node, capabilities)
    request.node._driver = driver
    request.addfinalizer(lambda: driver.quit())
    return driver
```
