### ISSUE TITLE
don't close the browser after test finish

### ISSUE THREAD

**Issue by rarelam** [mozilla/pytest-mozwebqa#73]
Hi, I'm don't sure if this plugin capable to no-close browser after test finish. Sometimes I am writing test locally and want to know what is failing without start the browser manually.

**Comment by lkisma1** [comment]
I understand @davehunt 's reservation to put this switch in, but, after seeing @andykeller 's process for creating script, much like @rarelam 's concerns mentioned in the first comment, I can see the frustration of how development is accomplished.

Originally, we altered our copy of mozwebqa 1.3 to remove the close directive. The trouble was the features of 1.6 that make Saucelabs integration so easy weren't really available.

After reading the py.test docs a lot, I finally found a decent workaround to help @andykeller : 
use the "--pdb" command-line switch when running the script.

It'll spawn the PDB, but, more importantly, it'll keep the browser window open for inspection...

**Comment by davehunt** [comment]
I have been keeping this in mind while working on the next iteration of this plugin. I'm currently thinking of supporting an INI file setting to prevent closing the browser windows. It might look something like:

```INI
[pytest]
selenium_close = false
```

**Comment by davehunt** [comment]
I've implemented a potential solution [in pytest-selenium](https://github.com/davehunt/pytest-selenium/compare/orphan). I'm keen to get feedback on this.

**Comment by davehunt** [comment]
hmm.. on the other hand, overriding the `selenium` fixture should work too, and allows for much more flexibility:

```python
import pytest
@pytest.fixture
def selenium(request, _sensitive_skipping, capabilities):
    from pytest_selenium.driver import start_driver
    driver = start_driver(request.node, capabilities)
    request.node._driver = driver
    return driver
```

**Comment by davehunt** [comment]
Closing this, as the earlier comment provides a solution for the upcoming pytest-selenium plugin.
