### ISSUE TITLE
Log file for WebDriver

### ISSUE THREAD

**Issue by birdsarah** [mozilla/pytest-mozwebqa#79]
Hi @davehunt , a quick question: Am I right in thinking that there is no logfile available for WebDriver in the same way that it is for RC and so the @pytest.mark.public won't have any effect on the output?

**Comment by davehunt** [comment]
This has been implemented in https://github.com/davehunt/pytest-mozwebqa/commit/f7e00fa0d218500876fc114e913d6590f174b8f0 and will be available in the next version (incarnation) of the plugin. See https://github.com/mozilla/pytest-mozwebqa/pull/155 for the relevant pull request.

**Comment by davehunt** [comment]
Okay, this is under way for pytest-selenium here: https://github.com/davehunt/pytest-selenium/pull/30
