### ISSUE TITLE
Implicit Waits - document not selenium standard.

### ISSUE THREAD

**Issue by birdsarah** [mozilla/pytest-mozwebqa#80]
Hi,

I was talking to @zacc about WebDriver waits and he pointed me to his [blog post](https://blog.mozilla.org/webqa/2012/07/12/webdrivers-implicit-wait-and-deleting-elements/) where he talks about amongst other things, the default being 10 seconds on an Implicit Wait, and the workaround he has for it.  

As I've come from Java selenium, this was not what I was used to and I checked the documentation here: http://seleniumhq.org/docs/04_webdriver_advanced.html and the default is 0 seconds. 

It turns out, a new default of 10 seconds is set in the pytest-mozwebqa module here: https://github.com/davehunt/pytest-mozwebqa/blob/master/pytest_mozwebqa/selenium_client.py#L49

As a newcomer to pytest-mozwebqa but someone that knows a little selenium, this was a little confusing.

I'd like to do a pull request to update the Readme to make this clearer to noobs like me, but I was wondering if someone could give some extra background on why this default and how its useful before i write it up.

Thanks.

**Comment by davehunt** [comment]
In [pytest-selenium](https://github.com/davehunt/pytest-selenium/) we no longer modify the implicit wait timeout. I personally recommend avoiding implicit waits, but if needed they can now be set by overriding the `selenium` fixture.
