### ISSUE TITLE
Report style modifications

### ISSUE THREAD

**Issue by birdsarah** [mozilla/pytest-mozwebqa#85]
Following on from issue #74, suggest the following small potential style modifications to the report:
* make the text black to increase contrast for readability (note dave's screen capture during a presentation when you couldn't see the text)
* Re-jig the summaries at the top of the page to bring the test results higher up the screen
* Make a table out of the summary
* Make the actual error text in the log output bigger and bolder

An example of these modifications can be seen here: http://birdsarah.github.com/pytest-mozwebqa-report-proto/prototype/ (this is from an earlier prototype, so ignore the results table)

**Comment by davehunt** [comment]
Development of the HTML report has been moved to [pytest-html](https://github.com/davehunt/pytest-html). I think this is still a valid feature request, so please feel free to raise it again.
