### ISSUE TITLE
Ability to hide / filter rows in report

### ISSUE THREAD

**Issue by birdsarah** [mozilla/pytest-mozwebqa#86]
Based on the prototype here: http://birdsarah.github.com/pytest-mozwebqa-report-proto/prototype/

Suggest adding the ability to:
* hide results of a certain test class e.g. pass / fail etc.
* hide the debug rows for a compact view

**Comment by davehunt** [comment]
Development of the HTML report has been moved to [pytest-html](https://github.com/davehunt/pytest-html). I think this is still a valid feature request, so please feel free to raise it again.
