### ISSUE TITLE
Do we want to set max_retries to a number higher than 0?

### ISSUE THREAD

**Issue by stephendonner** [mozilla/pytest-mozwebqa#89]
We see failures in test suites (like mcom-tests and mdn-tests) where we don't retry a requests.get() request, and we have max_retries set to 0, I believe:

                        retries=self.config.get('max_retries', 0),

Should we set it to 5?  Is there any harm in doing so?

**Comment by davehunt** [comment]
It looks like requests has changed a bit since this was opened. As far as I can tell the default retries is now 3, and I don't think we've seen too many failures related to this recently.
